version: '3.8'

services:

  # mosquitto:
  #   image: eclipse-mosquitto:2
  #   container_name: mosquitto-guilherme
  #   ports:
  #     - "1884:1884"  # Porta MQTT padrão
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config      
  #   networks:
  #     - mqtt-net
  mongodb:
    image: mongo:4.4
    container_name: mongodb-ipiranga
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb_data:/data/db
    # networks:
    #   - mqtt-net

  servidor-mqtt:
    build:
      context: .
      dockerfile: Dockerfile-servidor-ipiranga
    ports:
     #- "1884:1884"
      - "8084:8084"
    environment:
      - DB_HOST=mongodb://172.16.201.9:27017
    # networks:
    #   - mqtt-net
    container_name: servidor-mqtt-ipiranga
    depends_on:
      - mongodb

# networks:
#   mqtt-net:
#     driver: bridge

# volumes:
#   mongodb_data: