version: '3.8'

services:

  # mosquitto:
  #   image: eclipse-mosquitto:2
  #   container_name: mosquitto-guilherme
  #   ports:
  #     - "1884:1884"  # Porta MQTT padrão
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config      
  #   networks:
  #     - mqtt-net
  mongodb:
    image: mongo:4.4
    container_name: mongodb-22
    ports:
      - "27017:27017"
    # volumes:
      # - mongodb_data:/data/db
        # - /home/tec502/Downloads/gopbl-2-comunicacao-mqtt
    # networks:
    #   - mqtt-net

  servidor-mqtt-22:
    build:
      context: .
      dockerfile: Dockerfile-servidor
    ports:
      # - "1884:1884"
      - "8083:8083"
    environment:
      - DB_HOST=mongodb://172.16.201.2:27017
    # networks:
    #   - mqtt-net
    container_name: servidor-mqtt
    depends_on:
      - mongodb

# networks:
#   mqtt-net:
#     driver: bridge

# volumes:
#   mongodb_data: