version: '3.8'

services:

  # mosquitto:
  #   image: eclipse-mosquitto:2
  #   container_name: mosquitto-guilherme
  #   ports:
  #     - "1884:1884"  # Porta MQTT padrão
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config      
  #   networks:
  #     - mqtt-net
  mongodb:
    image: mongo:4.4
    container_name: mongodb-shell
    ports:
      - "27017:27017"
    # volumes:
      # - mongodb_data:/data/db
    networks:
      - mqtt-net

  servidor-mqtt-shell:
    build:
      context: .
      dockerfile: Dockerfile-servidor-shell
    ports:
      # - "1884:1884"
      - "8085:8085"
    environment:
      - DB_HOST=mongodb
    networks:
      - mqtt-net
    container_name: servidor-mqtt-shell
    depends_on:
      - mongodb

networks:
  mqtt-net:
    driver: bridge

# volumes:
#   mongodb_data: